"""Render models/docs/lineage.md from a dbt manifest.

Usage (after `dbt parse` or `dbt docs generate`):
    python scripts/generate_lineage_doc.py [path/to/manifest.json]
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT = "the_tuva_project_demo"
OUTPUT = ROOT / "models" / "docs" / "lineage.md"


def load_manifest(path):
    with open(path) as f:
        return json.load(f)


def upstream(manifest, unique_id):
    nodes = {**manifest["nodes"], **manifest["exposures"]}
    seen = set()
    stack = list(nodes[unique_id]["depends_on"]["nodes"])
    while stack:
        node_id = stack.pop()
        if node_id in seen or node_id not in manifest["nodes"]:
            continue
        seen.add(node_id)
        stack.extend(manifest["nodes"][node_id].get("depends_on", {}).get("nodes", []))
    return seen


def short(unique_id):
    return unique_id.split(".")[-1]


def matrix(title, intro, rows, exposures, deps):
    header = "| " + title + " | " + " | ".join(f"`{short(e)}`" for e in exposures) + " |"
    divider = "|---" * (len(exposures) + 1) + "|"
    lines = [intro, "", header, divider]
    for row in rows:
        cells = ["x" if row in deps[e] else "" for e in exposures]
        lines.append(f"| `{short(row)}` | " + " | ".join(cells) + " |")
    return lines


def render(manifest):
    exposures = sorted(
        e for e, v in manifest["exposures"].items() if v["package_name"] == PROJECT
    )
    deps = {e: upstream(manifest, e) for e in exposures}
    all_upstream = set().union(*deps.values())

    demo_inputs = sorted(
        n for n in all_upstream
        if manifest["nodes"][n]["package_name"] == PROJECT
        and manifest["nodes"][n]["resource_type"] in ("seed", "model")
    )
    core_models = sorted(
        n for n in all_upstream
        if manifest["nodes"][n]["resource_type"] == "model"
        and short(n).startswith("core__")
        and not short(n).startswith("core__stg_")
    )

    lines = [
        "{% docs __overview__ %}",
        "# The Tuva Project Demo",
        "",
        "This project loads a 1,000 patient synthetic claims and clinical dataset into the",
        "input layer and runs the Tuva package on it. This page maps the **downstream",
        "artifacts (exposures)** that consume the Tuva data marts back to the models and",
        "demo inputs they depend on. Open any exposure under *Exposures* in the sidebar, or",
        "use the lineage graph (bottom-right icon) with `+exposure:<name>` to see its full",
        "upstream DAG.",
        "",
        "*This page is generated by `scripts/generate_lineage_doc.py`; do not edit by hand.*",
        "",
        "## Exposures",
        "",
        "| Exposure | Type | Maturity | Directly depends on | Upstream nodes |",
        "|---|---|---|---|---|",
    ]
    for e in exposures:
        exp = manifest["exposures"][e]
        direct = ", ".join(f"`{short(n)}`" for n in sorted(exp["depends_on"]["nodes"]))
        label = exp.get("label") or exp["name"]
        lines.append(
            f"| **{label}** (`{exp['name']}`) | {exp['type']} | {exp.get('maturity') or ''}"
            f" | {direct} | {len(deps[e])} |"
        )

    lines += [""] + matrix(
        "Demo input",
        "## Demo inputs → exposures\n\nWhich exposures are affected if a seed or input "
        "layer model in this repo changes.",
        demo_inputs, exposures, deps,
    )
    lines += [""] + matrix(
        "Core model",
        "## Tuva core models → exposures\n\nWhich exposures read (directly or transitively) "
        "from each Tuva core model.",
        core_models, exposures, deps,
    )
    lines += ["", "{% enddocs %}", ""]
    return "\n".join(lines)


def main():
    manifest_path = sys.argv[1] if len(sys.argv) > 1 else ROOT / "target" / "manifest.json"
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(load_manifest(manifest_path)))
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
